-- Weekly financial summaries generated by the OrchestratorAgent
CREATE TABLE IF NOT EXISTS weekly_summaries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  week_start DATE NOT NULL,
  week_end DATE NOT NULL,
  net_worth NUMERIC(14,2),
  net_worth_change NUMERIC(14,2),
  net_worth_change_pct NUMERIC(6,2),
  total_income NUMERIC(12,2) DEFAULT 0,
  total_spending NUMERIC(12,2) DEFAULT 0,
  top_categories JSONB DEFAULT '[]',        -- [{category, amount, budget_pct}]
  portfolio_return_pct NUMERIC(6,2),
  insights_generated INTEGER DEFAULT 0,
  highlights TEXT[],                         -- key bullet points
  raw_data JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (week_start)
);

CREATE INDEX IF NOT EXISTS idx_weekly_summaries_date ON weekly_summaries(week_start DESC);
